scenario_cfg:
  dataset_name: OccTextCfAskGender
  base_data_path: GenderBias-VL/exp_flip_bleach/xl_bleach_person
  meta_file: GenderBias-VL/construction/vq_generation/test_meta_file_close/Lbias/occ_test_text_cf_ask_gender.json
  ppl: True
  option_content: False

eval_cfg:
  instruction_cfg: 
    query_type: query_pool
    query_assigned_ids: 0 # otter 1 # use for vqa_prompts
    template_assigned_ids: 0 # otter 1 # use for vqa_answer_templates
  inferencer_cfg:
    inferencer_type: Direct #Direct #
    batch_size: 32
    CoT: False
    max_new_tokens: 256
  metric_cfg:
    metric_type: basic